language: android
jdk: oraclejdk7

android:
    components:
        - android-19
        - build-tools-19.0.3
        - extra-android-support
    licenses:
        - android-sdk-license-bcbbd656

script:
    - ./gradlew build -q
